name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: TeslaVideoCenter
      
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Publish Windows
      run: dotnet publish --runtime win10-x64 --configuration Release
    - name: Publish MacOS
      run: dotnet msbuild -t:BundleApp -p:RuntimeIdentifier=osx-x64 -property:Configuration=Release
    - name: Archive MacOS App
      uses: actions/upload-artifact@v2
      with:
        name: MacOS-App
        path: 'bin/Release/netcoreapp3.1/osx-x64/publish/Tesla Video Center.app'
